### ISSUE TITLE
Site down with a nuxt related 500?

### ISSUE THREAD

**Issue by gee-forr** [stimulus-components/stimulus-components#84]
Hi there,

Apologies if this is the wrong place to post such issues, but it appears that the https://www.stimulus-components.com/ is broken.

It's returning a 500. Even though it's a server side error, I thought it might be my browser. I tried with a number of different browsers, and they're all showing the same issue.

![image](https://github.com/stimulus-components/stimulus-components/assets/345730/1cc4ec1b-2314-419c-96de-c35484c95ebc)

**Comment by guillaumebriday-pa** [comment]
Thanks for reporting!

Just deployed a hot fix, it was because of the leap year, see: https://github.com/stimulus-components/stimulus-components/commit/2c6703cbd073d377903cef6fe46c69a13b8e8bed

With the previous method, the number of days was 366 and `https://api.npmjs.org/downloads/point` would return a 500 and `useFetch` didn't catch it properly.

We need to check the API response, I'll do it in `new-ui`!
